services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  apinodeminio:
    image: apinodeminio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_REGION: ${MINIO_REGION}
    ports:
      - "3000:3000"
    depends_on:
      - minio

volumes:
  minio_data: