version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    ports:
      - "9000:9000"   # API do MinIO (S3 compatível)
      - "9001:9001"   # Console Web do MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
