### 1. Verificar se a API está rodando
GET http://localhost:3000/


### 2. Listar arquivos do bucket
GET http://localhost:3000/files


### 3. Upload de arquivo
# Para executar este teste, altere o caminho abaixo
# para um arquivo existente no seu computador.

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="21577.jpg"
Content-Type: image/jpeg

< C:\Users\Breno\Downloads\21577.jpg
--Boundary--


### 4. Visualizar ou baixar arquivo
# Troque a key abaixo por uma key retornada no upload/listagem

GET http://localhost:3000/files/1788927474465-21577.jpg


### 5. Remover arquivo
# Troque a key abaixo por uma key existente

DELETE http://localhost:3000/files/1788927474465-21577.jpg